// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRbs7ltz1GE6S6HO9bAaqWepgtdjxd0B8',
    appId: '1:918087502215:web:d44aef2a687dab0669eb22',
    messagingSenderId: '918087502215',
    projectId: 'crypto-coin-40d81',
    authDomain: 'crypto-coin-40d81.firebaseapp.com',
    storageBucket: 'crypto-coin-40d81.firebasestorage.app',
    measurementId: 'G-ZMGPQHD3K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzp3I5sFBL0MkouAt6ldVKPGuIXn15p0',
    appId: '1:918087502215:android:b818474c38c0ba8d69eb22',
    messagingSenderId: '918087502215',
    projectId: 'crypto-coin-40d81',
    storageBucket: 'crypto-coin-40d81.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTlfpACrUU_ggsdG4xPrPyaGtxMg4qs4Q',
    appId: '1:918087502215:ios:26f9d9f92b47cd8669eb22',
    messagingSenderId: '918087502215',
    projectId: 'crypto-coin-40d81',
    storageBucket: 'crypto-coin-40d81.firebasestorage.app',
    iosBundleId: 'com.hamid.cryptoCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRbs7ltz1GE6S6HO9bAaqWepgtdjxd0B8',
    appId: '1:918087502215:web:194372cd6a08366c69eb22',
    messagingSenderId: '918087502215',
    projectId: 'crypto-coin-40d81',
    authDomain: 'crypto-coin-40d81.firebaseapp.com',
    storageBucket: 'crypto-coin-40d81.firebasestorage.app',
    measurementId: 'G-987YEK4SS4',
  );
}
