// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQBQPPAyPF4ve-QG21M_Y2BFaQvyuMzU',
    appId: '1:824849125773:web:40b1202b2f8837f22a6dc4',
    messagingSenderId: '824849125773',
    projectId: 'crypto-coin-f8437',
    authDomain: 'crypto-coin-f8437.firebaseapp.com',
    storageBucket: 'crypto-coin-f8437.firebasestorage.app',
    measurementId: 'G-0TL5L2SELG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVg8zjMemdphTcM_DZyQlArQq7VHZbmIg',
    appId: '1:824849125773:android:c1c82a7c6b279e862a6dc4',
    messagingSenderId: '824849125773',
    projectId: 'crypto-coin-f8437',
    storageBucket: 'crypto-coin-f8437.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYkT9OTvPx3L_ljtRAoPHJ2angF0Txrw',
    appId: '1:824849125773:ios:6db669ed921388cf2a6dc4',
    messagingSenderId: '824849125773',
    projectId: 'crypto-coin-f8437',
    storageBucket: 'crypto-coin-f8437.firebasestorage.app',
    iosBundleId: 'com.hamid.cryptoCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQBQPPAyPF4ve-QG21M_Y2BFaQvyuMzU',
    appId: '1:824849125773:web:0482e8fc2db816512a6dc4',
    messagingSenderId: '824849125773',
    projectId: 'crypto-coin-f8437',
    authDomain: 'crypto-coin-f8437.firebaseapp.com',
    storageBucket: 'crypto-coin-f8437.firebasestorage.app',
    measurementId: 'G-FS3G7TKJ2C',
  );
}
